# Site settings
title: PORTFOLIO
email: XNIZDUCH@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  XNIZDUCH
baseurl: "" # the subpath of your site, e.g. /blog
logo: #"/images/logo/philolog_logo.png"
url: "www.dawidchudzinski.pl" # the base hostname & protocol for your site
twitter_username: 
github_username:  XNIZDUCH
google_analytics: G-4KMKFQMLFQ

# Build settings
markdown: kramdown
permalink: pretty
